# Generated by Django 5.2.14 on 2026-05-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_escola', models.TextField()),
                ('cidade', models.TextField()),
                ('nome_diretor', models.TextField()),
                ('cargo', models.TextField(default='Diretor(a)')),
                ('iniciais', models.TextField()),
                ('cor_avatar', models.TextField(default='#4f46e5')),
                ('foto_url', models.TextField(blank=True, default='')),
                ('depoimento', models.TextField()),
                ('estrelas', models.IntegerField(default=5)),
                ('ativo', models.IntegerField(default=1)),
                ('ordem', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'escolas',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('email', models.TextField(blank=True, default='')),
                ('telefone', models.TextField()),
                ('escola', models.TextField()),
                ('mensagem', models.TextField(blank=True, default='')),
                ('estado', models.TextField(default='novo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'leads',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escola_nome', models.TextField()),
                ('cidade', models.TextField(default='Angola')),
                ('pacote', models.TextField()),
                ('valor', models.FloatField(default=0)),
                ('metodo', models.TextField(default='Transferência Bancária')),
                ('pago_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pagamentos',
                'ordering': ['-pago_em'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('categoria', models.TextField(default='Outros')),
                ('resumo', models.TextField(blank=True, default='')),
                ('conteudo', models.TextField(blank=True, default='')),
                ('intro', models.TextField(blank=True, default='')),
                ('pontos', models.TextField(blank=True, default='[]')),
                ('imagem_url', models.TextField(blank=True, default='')),
                ('video_url', models.TextField(blank=True, default='')),
                ('autor', models.TextField(default='Equipa Super Escola')),
                ('publicado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'posts',
                'ordering': ['-publicado_em'],
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('chave', models.TextField(primary_key=True, serialize=False)),
                ('valor', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'settings',
            },
        ),
    ]
