# Generated by Django 5.2.14 on 2026-05-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('categoria', models.TextField(default='Geral')),
                ('resumo', models.TextField(blank=True, default='')),
                ('intro', models.TextField(blank=True, default='')),
                ('passos', models.TextField(blank=True, default='[]')),
                ('conteudo', models.TextField(blank=True, default='')),
                ('imagem_url', models.TextField(blank=True, default='')),
                ('autor', models.TextField(default='Equipa Super Escola')),
                ('publicado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'manuais',
                'ordering': ['-publicado_em'],
            },
        ),
    ]
